some error checking

diff --git a/shell_scripts/prsync b/shell_scripts/prsync
--- a/shell_scripts/prsync
+++ b/shell_scripts/prsync
@@ -23,10 +23,21 @@ njobs=$2
 fromdir=$3
 todir=$4
 
+if [[ -e "$tmpdir" ]]; then
+    echo "error: tmpdir already exists: $tmpdir"
+    exit 1
+fi
+
 mkdir -p "$tmpdir"
+
+if [[ ! -e "$tmpdir" ]]; then
+    echo "could not make temp dir: $tmpdir"
+    exit 1
+fi
+
 pushd "$tmpdir"
 
-# shuffle to make sure we don't put all the small files in one job
+# shuffle to make sure the jobs are all about the same length
 flist="flist.txt"
 find "$fromdir" -type f -exec basename {} \; | shuf > "$flist"
 
@@ -34,24 +45,25 @@ nfiles=$(wc -l "$flist" | awk '{print $1}')
 
 if [[ $nfiles == "0" ]]; then
     echo "no files found"
-    exit 0
-fi
-
-# If the number of files is less than the number of jobs, set the
-# number of jobs to the number of files and split size to 1
-if [[ $nfiles -lt $njobs ]]; then
-    njobs="$nfiles"
-    nsplit=1
 else
-    nsplit=$((nfiles/njobs))
+
+    # If the number of files is less than the number of jobs, set the
+    # number of jobs to the number of files and split size to 1
+    if [[ $nfiles -lt $njobs ]]; then
+        njobs="$nfiles"
+        nsplit=1
+    else
+        nsplit=$((nfiles/njobs))
+    fi
+
+    split -l "$nsplit" "$flist"
+
+    #wc "$flist"
+    #wc x*
+
+    parallel -u -j "$njobs" "rsync -av --files-from={} $fromdir/ $todir/" ::: x*
+
 fi
-
-split -l "$nsplit" "$flist"
-
-wc "$flist"
-wc x*
-
-parallel -u -j "$njobs" "rsync -av --files-from={} $fromdir/ $todir/" ::: x*
 
 popd
 rm -r $tmpdir
